import { StyleSheet } from "react-native";

export const getStyles = (darkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: darkMode ? "#1A1A2E" : "#F4F3FF",
      paddingBottom: 20,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 12,
      backgroundColor: darkMode ? "#16213E" : "#fff",
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      elevation: 4,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: darkMode ? "#fff" : "#2D2D2D",
    },
    formContainer: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    image: {
      width: "100%",
      height: 200,
      borderRadius: 16,
      marginBottom: 16,
    },
    imagePlaceholder: {
      width: "100%",
      height: 160,
      borderRadius: 16,
      backgroundColor: darkMode ? "#16213E" : "#fff",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
      elevation: 2,
    },
    imagePlaceholderText: {
      color: darkMode ? "#555" : "#ccc",
      fontSize: 14,
      marginTop: 8,
    },
    inputContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: darkMode ? "#16213E" : "#fff",
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 12,
      elevation: 2,
      gap: 8,
    },
    input: {
      flex: 1,
      fontSize: 15,
      color: darkMode ? "#fff" : "#333",
    },
    notesInput: {
      minHeight: 80,
      textAlignVertical: "top",
    },
    errorText: {
      color: "#E53935",
      fontSize: 12,
      marginTop: -8,
      marginBottom: 8,
      marginLeft: 4,
    },
    locationRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
      gap: 6,
    },
    address: {
      fontSize: 14,
      color: "#6C63FF",
      fontWeight: "500",
    },
    photoButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#6C63FF",
      padding: 16,
      borderRadius: 14,
      marginBottom: 12,
      gap: 8,
      elevation: 3,
    },
    saveButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#4CAF50",
      padding: 16,
      borderRadius: 14,
      gap: 8,
      elevation: 3,
    },
    buttonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 15,
    },
  });