import { StyleSheet } from "react-native";

export const getStyles = (darkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: darkMode ? "#1A1A2E" : "#F4F3FF",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 12,
      backgroundColor: darkMode ? "#16213E" : "#fff",
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      elevation: 4,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: darkMode ? "#fff" : "#2D2D2D",
    },
    formContainer: {
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 40,
      gap: 16,
    },
    imageWrapper: {
      borderRadius: 16,
      overflow: "hidden",
    },
    image: {
      width: "100%",
      height: 200,
      borderRadius: 16,
    },
    removeImageButton: {
      position: "absolute",
      top: 8,
      right: 8,
      backgroundColor: "#fff",
      borderRadius: 50,
      elevation: 4,
    },
    imagePlaceholder: {
      width: "100%",
      height: 160,
      borderRadius: 16,
      backgroundColor: darkMode ? "#16213E" : "#fff",
      justifyContent: "center",
      alignItems: "center",
      elevation: 2,
    },
    imagePlaceholderError: {
      borderWidth: 1.5,
      borderColor: "#E53935",
    },
    locationRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: darkMode ? "#16213E" : "#fff",
      padding: 10,
    },
    address: {
      fontSize: 14,
      color: "#6C63FF",
      fontWeight: "500",
      flexShrink: 1,
    },
    inputContainer: {
      flexDirection: "row",
      alignItems: "flex-start",
      backgroundColor: darkMode ? "#16213E" : "#fff",
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 12,
      elevation: 2,
      gap: 8,
    },
    inputError: {
      borderWidth: 1.5,
      borderColor: "#E53935",
    },
    inputIcon: {
      marginTop: 2,
    },
    input: {
      flex: 1,
      fontSize: 15,
      color: darkMode ? "#fff" : "#333",
    },
    notesInput: {
      minHeight: 80,
      textAlignVertical: "top",
    },
    errorText: {
      color: "#E53935",
      fontSize: 12,
      marginTop: -8,
      marginLeft: 4,
    },
    photoErrorText: {
      color: "#E53935",
      fontSize: 12,
      marginTop: 4, 
      marginLeft: 4,
    },
    photoButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#6C63FF",
      padding: 16,
      borderRadius: 14,
      gap: 8,
      elevation: 3,
    },
    saveButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#4CAF50",
      padding: 16,
      borderRadius: 14,
      gap: 8,
      elevation: 3,
    },
    buttonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 15,
    },
  });